a=input('enter time of 30 hourly observation')
b=input('enter time of origin:')
c=input('where the Meter go:')
d=str(input('wind speed v direction:'))
e=input('cloud_1 type:')
f=input('cloud_2 type:')
g=input('cloud_3 type/NSC:')
h=input('cloud_4 type/SKC:')
i=input('dry-bulb temp:')
j=input('wet-bulb temp:')
k=eval(input('C.L.P of digital bar:'))
l=eval(input('QNH of digital bar :'))
m=input('Dew point:')
n=input('relative humidity:')
o=input('present weather:').upper()
p=input('visibility/COVAK:')
q=input('evaporation cups:')
r=input('Rainfall:')



print(a,'z',end=',')
print(b,'z'end=',')
print(c,end=',')
print(d,'KT',end=',')
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)
print(k,end='')
print(k/70)
print(l,end='')
print(l/23)
print(m)
print(n)
print(o)
print(p,'Km')
print(q)
